[package]
name = "redis_ts"
version = "0.1.0"
authors = ["protom <office@protom.eu>"]
edition = "2018"

[dependencies]
redis = "0.16.0"

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
futures = "0.3.5"
async-std = "1.6.0"
